import { randomUUID } from "node:crypto";
import { CommandStatus, PrismaClient } from "@prisma/client";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/auth", () => ({
  getDevContext: vi.fn(),
}));

import { getDevContext } from "@/lib/auth";
import { POST as simulateAutoSend } from "@/app/api/auto-send/simulate/route";
import { GET as getSendEvent } from "@/app/api/send-events/[id]/route";

const prisma = new PrismaClient();

let organisationId = "";
let ownerUserId = "";
let commandId = "";

beforeAll(async () => {
  const suffix = randomUUID().slice(0, 8);
  const org = await prisma.organisation.create({
    data: {
      name: `Send Event Org ${suffix}`,
      slug: `send-event-org-${suffix}`,
      plan: "test",
    },
  });
  organisationId = org.id;

  const owner = await prisma.user.create({
    data: {
      organisationId,
      email: `send-owner-${suffix}@example.com`,
      name: "Send Owner",
      role: "owner",
    },
  });
  ownerUserId = owner.id;

  const command = await prisma.actionCommand.create({
    data: {
      organisationId,
      name: `send_event_low_${suffix}`,
      description: "Send event command",
      inputSchemaJson: { ticket_id: "string", amount: "number", reason: "string" },
      outputSchemaJson: { ok: "boolean" },
      executionStrategy: "api_first_browser_fallback",
      riskLevel: "low",
      approvalRulesJson: null,
      successCondition: "ok",
      failureConditionsJson: [],
      sourceEvidenceJson: ["test"],
      status: CommandStatus.published,
    },
  });
  commandId = command.id;

  await prisma.approvalPolicy.create({
    data: {
      organisationId,
      name: "Send Event Policy",
      status: "active",
      isDefault: true,
      policyJson: {
        thresholds: { amount_greater_than: 200 },
        scenario_gates: ["refund_flow"],
        auto_send: {
          confidence_threshold: 0.9,
          scenario_allowlist: ["refund_flow"],
          zero_tolerance_violations: ["policy_violation"],
        },
      },
    },
  });
});

beforeEach(() => {
  vi.mocked(getDevContext).mockResolvedValue({
    organisationId,
    userId: ownerUserId,
    user: {
      id: ownerUserId,
      email: "owner@example.com",
      name: "Owner",
      role: "owner",
    },
  });
});

afterAll(async () => {
  await prisma.auditLog.deleteMany({ where: { organisationId } });
  await prisma.sendEvent.deleteMany({ where: { organisationId } });
  await prisma.approvalPolicy.deleteMany({ where: { organisationId } });
  await prisma.actionCommand.deleteMany({ where: { organisationId } });
  await prisma.user.deleteMany({ where: { organisationId } });
  await prisma.organisation.deleteMany({ where: { id: organisationId } });
  await prisma.$disconnect();
});

describe("send events API", () => {
  it("returns immutable send event snapshot generated by auto-send simulation", async () => {
    const simulateRes = await simulateAutoSend(
      new Request("http://localhost/api/auto-send/simulate", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          command_id: commandId,
          scenario: "refund_flow",
          confidence: 0.95,
          violations: [],
          input: { amount: 100 },
        }),
      }),
    );
    expect(simulateRes.status).toBe(200);
    const simulateBody = await simulateRes.json();
    const sendEventId = simulateBody.context.send_event_id as string;

    const getRes = await getSendEvent(new Request(`http://localhost/api/send-events/${sendEventId}`), {
      params: Promise.resolve({ id: sendEventId }),
    });
    expect(getRes.status).toBe(200);
    const getBody = await getRes.json();
    expect(getBody.send_event.id).toBe(sendEventId);
    expect(getBody.send_event.source).toBe("auto_send_simulation");
    expect(getBody.send_event.delivery_state).toBe("simulated_not_dispatched");
    expect(getBody.send_event.decision_status).toBe("allow_auto_send");
  });

  it("returns not_found when send event id is unknown", async () => {
    const missingId = "missing-send-event-id";
    const res = await getSendEvent(new Request(`http://localhost/api/send-events/${missingId}`), {
      params: Promise.resolve({ id: missingId }),
    });
    expect(res.status).toBe(404);
  });
});
